server/mhn/__init__.py
from urlparse import urljoin

from flask import Flask, request, jsonify, abort, url_for, session
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.security import Security, SQLAlchemyUserDatastore
from flask.ext.security.utils import encrypt_password as encrypt
from flask.ext.mail import Mail
from werkzeug.contrib.atom import AtomFeed
import xmltodict
import uuid
import random
import string
from flask_wtf.csrf import CsrfProtect
csrf = CsrfProtect()

db = SQLAlchemy()
# After defining `db`, import auth models due to
# circular dependency.
from mhn.auth.models import User, Role, ApiKey
user_datastore = SQLAlchemyUserDatastore(db, User, Role)


mhn = Flask(__name__)
mhn.config.from_object('config')
csrf.init_app(mhn)

# Email app setup.
mail = Mail()
mail.init_app(mhn)

# Registering app on db instance.
db.init_app(mhn)

# Setup flask-security for auth.
Security(mhn, user_datastore)

# Registering blueprints.
from mhn.api.views import api
mhn.register_blueprint(api)

from mhn.ui.views import ui
mhn.register_blueprint(ui)

from mhn.auth.views import auth
mhn.register_blueprint(auth)

# Trigger templatetag register.
from mhn.common.templatetags import format_date
mhn.jinja_env.filters['fdate'] = format_date

from mhn.auth.contextprocessors import user_ctx
mhn.context_processor(user_ctx)

from mhn.common.contextprocessors import config_ctx
mhn.context_processor(config_ctx)

import logging
from logging.handlers import RotatingFileHandler

mhn.logger.setLevel(logging.INFO)
formatter = logging.Formatter(
      '%(asctime)s -  %(pathname)s - %(message)s')
handler = RotatingFileHandler(
        mhn.config['LOG_FILE_PATH'], maxBytes=10240, backupCount=5)
handler.setLevel(logging.INFO)
handler.setFormatter(formatter)
mhn.logger.addHandler(handler)
if mhn.config['DEBUG']:
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    console.setFormatter(formatter)
    mhn.logger.addHandler(console)


@mhn.route('/feed.json')
def json_feed():
    feed_content = get_feed().to_string()
    return jsonify(xmltodict.parse(feed_content))


@mhn.route('/feed.xml')
def xml_feed():
    return get_feed().get_response()


def makeurl(uri):
    baseurl = mhn.config['SERVER_BASE_URL']
    return urljoin(baseurl, uri)


def get_feed():
    from mhn.common.clio import Clio
    from mhn.auth import current_user
    authfeed = mhn.config['FEED_AUTH_REQUIRED']
    if authfeed and not current_user.is_authenticated():
        abort(404)
    feed = AtomFeed('MHN HpFeeds Report', feed_url=request.url,
                    url=request.url_root)
    sessions = Clio().session.get(options={'limit': 1000})
    for s in sessions:
        feedtext = u'Sensor "{identifier}" '
        feedtext += '{source_ip}:{source_port} on sensorip:{destination_port}.'
        feedtext = feedtext.format(**s.to_dict())
        feed.add('Feed', feedtext, content_type='text',
                 published=s.timestamp, updated=s.timestamp,
                 url=makeurl(url_for('api.get_session', session_id=str(s._id))))
    return feed


def create_clean_db():
    """
    Use from a python shell to create a fresh database.
    """
    with mhn.test_request_context():
        db.create_all()
        # Creating superuser entry.
        superuser = user_datastore.create_user(
                email=mhn.config.get('SUPERUSER_EMAIL'),
                password=encrypt(mhn.config.get('SUPERUSER_PASSWORD')))
        adminrole = user_datastore.create_role(name='admin', description='')
        user_datastore.add_role_to_user(superuser, adminrole)
        user_datastore.create_role(name='user', description='')
        db.session.flush()

        apikey = ApiKey(user_id=superuser.id, api_key=str(uuid.uuid4()).replace("-", ""))
        db.session.add(apikey)
        db.session.flush()

        from os import path

        from mhn.api.models import DeployScript, RuleSource
        from mhn.tasks.rules import fetch_sources
        # Creating a initial deploy scripts.
        # Reading initial deploy script should be: ../../scripts/
        #|-- deploy_conpot.sh
        #|-- deploy_dionaea.sh
        #|-- deploy_snort.sh
        #|-- deploy_kippo.sh
        deployscripts = {
            'Ubuntu - Conpot': path.abspath('../scripts/deploy_conpot.sh'),
            'Ubuntu - Dionaea': path.abspath('../scripts/deploy_dionaea.sh'),
            'Ubuntu - Snort': path.abspath('../scripts/deploy_snort.sh'),
            'Ubuntu - cowrie': path.abspath('../scripts/deploy_cowrie.sh'),
            'Ubuntu/Raspberry Pi - Kippo': path.abspath('../scripts/deploy_kippo.sh'),
            'Ubuntu - Amun': path.abspath('../scripts/deploy_amun.sh'),
            'Ubuntu - Glastopf': path.abspath('../scripts/deploy_glastopf.sh'),
            'Ubuntu - Wordpot': path.abspath('../scripts/deploy_wordpot.sh'),
            'Ubuntu - Shockpot': path.abspath('../scripts/deploy_shockpot.sh'),
            'Ubuntu - p0f': path.abspath('../scripts/deploy_p0f.sh'),
            'Ubuntu - Suricata': path.abspath('../scripts/deploy_suricata.sh'),
            'Ubuntu - ElasticHoney': path.abspath('../scripts/deploy_elastichoney.sh'),
            'Raspberry Pi - Dionaea': path.abspath('../scripts/deploy_raspberrypi.sh'),
            'Ubuntu - Dionaea with HTTP': path.abspath('../scripts/deploy_dionaea_http.sh'),
            'Ubuntu - Kippo as vulnerable Juniper Netscreen': path.abspath('../scripts/deploy_kippo_as_juniper.sh'),
            'Ubuntu - Shockpot Sinkhole': path.abspath('../scripts/deploy_shockpot_sinkhole.sh'),
            'Redhat/Centos - Kippo': path.abspath('../scripts/deploy_kippo-centos.sh'),
        }
        for honeypot, deploypath in deployscripts.iteritems():

            with open(deploypath, 'r') as deployfile:
                initdeploy = DeployScript()
                initdeploy.script = deployfile.read()
                initdeploy.notes = 'Initial deploy script for {}'.format(honeypot)
                initdeploy.user = superuser
                initdeploy.name = honeypot
                db.session.add(initdeploy)

        # Creating an initial rule source.
        rules_source = mhn.config.get('SNORT_RULES_SOURCE')
        if not mhn.config.get('TESTING'):
            rulesrc = RuleSource()
            rulesrc.name = rules_source['name']
            rulesrc.uri = rules_source['uri']
            rulesrc.name = 'Default rules source'
            db.session.add(rulesrc)
            db.session.commit()
            fetch_sources()

server/mhn/api/__init__.py
class APIModel(object):
    @classmethod
    def fields(cls):
        return cls.all_fields.keys()

    @classmethod
    def editable_fields(cls):
        return cls._make_field_list('editable')

    @classmethod
    def required_fields(cls):
        return cls._make_field_list('required')

    @classmethod
    def _make_field_list(cls, prop):
        """
        Returns a list of field names that have the property
        `prop` in the `all_fields` dictionary defined at
        class level.
        """
        return [f for f, e in cls.all_fields.items() if e.get(prop, False)]

    @classmethod
    def check_required(cls, payload):
        """
        Returns a list of required fields that are
        missing from the dictionary object `payload`.
        """
        missing = []
        for field in cls.required_fields():
            if (field not in payload) or payload.get(field) == '':
                missing.append(field)
        return missing

server/mhn/api/views.py
import json
from StringIO import StringIO
import csv

from uuid import uuid1

from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from flask import Blueprint, request, jsonify, make_response
from bson.errors import InvalidId

from mhn import db, csrf
from mhn.api import errors
from mhn.api.models import (
        Sensor, Rule, DeployScript as Script,
        DeployScript, RuleSource)
from mhn.api.decorators import deploy_auth, sensor_auth, token_auth
from mhn.common.utils import error_response
from mhn.common.clio import Clio
from mhn.auth import current_user, login_required


api = Blueprint('api', __name__, url_prefix='/api')


# Endpoints for the Sensor resource.
@api.route('/sensor/', methods=['POST'])
@csrf.exempt
@deploy_auth
def create_sensor():
    missing = Sensor.check_required(request.json)
    if missing:
        return error_response(
                errors.API_FIELDS_MISSING.format(missing), 400)
    else:
        sensor = Sensor(**request.json)
        sensor.uuid = str(uuid1())
        sensor.ip = request.remote_addr
        Clio().authkey.new(**sensor.new_auth_dict()).post()
        try:
            db.session.add(sensor)
            db.session.commit()
        except IntegrityError:
            return error_response(
                    errors.API_SENSOR_EXISTS.format(request.json['name']), 400)
        else:
            return jsonify(sensor.to_dict())

@api.route('/sensor/', methods=['GET'])
@token_auth
def get_sensors():
    req = request.args.to_dict()
    if 'api_key' in req:
        del req['api_key']
    resp = make_response(json.dumps([s.to_dict() for s in Sensor.query.filter_by(**req)]))
    resp.headers['Content-Type'] = "application/json"
    return resp

@api.route('/sensor/<uuid>/', methods=['PUT'])
@csrf.exempt
def update_sensor(uuid):
    sensor = Sensor.query.filter_by(uuid=uuid).first_or_404()
    for field in request.json.keys():
        if field in Sensor.editable_fields():
            setattr(sensor, field, request.json[field])
        elif field in Sensor.fields():
            return error_response(
                    errors.API_FIELD_NOT_EDITABLE.format(field), 400)
        else:
            return error_response(
                    errors.API_FIELD_INVALID.format(field), 400)
    else:
        try:
            db.session.commit()
        except IntegrityError:
            return error_response(
                    errors.API_SENSOR_EXISTS.format(request.json['name']), 400)
        return jsonify(sensor.to_dict())


@api.route('/sensor/<uuid>/', methods=['DELETE'])
@login_required
def delete_sensor(uuid):
    sensor = Sensor.query.filter_by(uuid=uuid).first_or_404()
    Clio().authkey.delete(identifier=uuid)
    db.session.delete(sensor)
    db.session.commit()
    return jsonify({})


@api.route('/sensor/<uuid>/connect/', methods=['POST'])
@csrf.exempt
@sensor_auth
def connect_sensor(uuid):
    sensor = Sensor.query.filter_by(uuid=uuid).first_or_404()
    sensor.ip = request.remote_addr
    db.session.commit()
    return jsonify(sensor.to_dict())


# Utility functions that generalize the GET
# requests of resources from Mnemosyne.
def _get_one_resource(resource, res_id):
    try:
        res = resource.get(_id=res_id)
    except InvalidId:
        res = None
    if not res:
        return error_response(errors.API_RESOURCE_NOT_FOUND, 404)
    else:
        return jsonify(res.to_dict())


def _get_query_resource(resource, query):
    options = {}
    if 'limit' in query:
        options['limit'] = int(query['limit'])

    results = list(resource.get(options, **query))
    return jsonify(
        data=[r.to_dict() for r in results],
        meta={
            'size': len(results),
            'query': query,
            'options': options
        }
    )
# Now let's make use these methods in the views.


@api.route('/feed/<feed_id>/', methods=['GET'])
@token_auth
def get_feed(feed_id):
    return _get_one_resource(Clio().hpfeed, feed_id)


@api.route('/session/<session_id>/', methods=['GET'])
@token_auth
def get_session(session_id):
    return _get_one_resource(Clio().session, session_id)


@api.route('/url/<url_id>/', methods=['GET'])
@token_auth
def get_url(url_id):
    return _get_one_resource(Clio().url, url_id)


@api.route('/file/<file_id>/', methods=['GET'])
@token_auth
def get_file(file_id):
    return _get_one_resource(Clio().file, file_id)

@api.route('/dork/<dork_id>/', methods=['GET'])
@token_auth
def get_dork(dork_id):
    return _get_one_resource(Clio().dork, dork_id)

@api.route('/metadata/<metadata_id>/', methods=['GET'])
@token_auth
def get_metadatum(metadata_id):
    return _get_one_resource(Clio().metadata, metadata_id)


@api.route('/feed/', methods=['GET'])
@token_auth
def get_feeds():
    return _get_query_resource(Clio().hpfeed, request.args.to_dict())


@api.route('/session/', methods=['GET'])
@token_auth
def get_sessions():
    return _get_query_resource(Clio().session, request.args.to_dict())


@api.route('/url/', methods=['GET'])
@token_auth
def get_urls():
    return _get_query_resource(Clio().url, request.args.to_dict())

@api.route('/file/', methods=['GET'])
@token_auth
def get_files():
    return _get_query_resource(Clio().file, request.args.to_dict())

@api.route('/dork/', methods=['GET'])
@token_auth
def get_dorks():
    return _get_query_resource(Clio().dork, request.args.to_dict())

@api.route('/metadata/', methods=['GET'])
@token_auth
def get_metadata():
    return _get_query_resource(Clio().metadata, request.args.to_dict())


@api.route('/top_attackers/', methods=['GET'])
@token_auth
def top_attackers():
    options = request.args.to_dict()
    limit = int(options.get('limit', '1000'))
    hours_ago = int(options.get('hours_ago', '4'))

    extra = dict(options)
    for name in  ('hours_ago', 'limit', 'api_key',):
        if name in extra:
            del extra[name]

    for name in options.keys():
        if name not in ('hours_ago', 'limit',):
            del options[name]
    results = Clio().session._tops(['source_ip', 'honeypot'], top=limit, hours_ago=hours_ago, **extra)
    return jsonify(
        data=results,
        meta={
            'size': len(results),
            'query': 'top_attackers',
            'options': options
        }
    )

@api.route('/attacker_stats/<ip>/', methods=['GET'])
@token_auth
def attacker_stats(ip):
    options = request.args.to_dict()
    hours_ago = int(options.get('hours_ago', '720')) # 30 days

    for name in options.keys():
        if name not in ('hours_ago', 'limit',):
            del options[name]
    results = Clio().session.attacker_stats(ip, hours_ago=hours_ago)
    return jsonify(
        data=results,
        meta={
            'query': 'attacker_stats',
            'options': options
        }
    )

def get_tags(rec):
    tags = [rec['honeypot'], rec['protocol'], 'port-{}'.format(rec['destination_port']),]

    meta = rec['meta']
    if len(meta) > 0:
        meta = meta[0]
    else:
        meta = {}

    for meta_key in ['app', 'os', 'link',]:
        value = meta.get(meta_key)
        if value:
            tags.append(value.replace(',', '').replace('\t', ' '))
    return tags

@api.route('/intel_feed.csv/', methods=['GET'])
@token_auth
def intel_feed_csv():
    fieldnames = ['source_ip', 'count', 'tags', ]
    results = get_intel_feed()
    outf = StringIO()
    wr = csv.DictWriter(outf, fieldnames=fieldnames, delimiter='\t', lineterminator='\n')
    wr.writeheader()
    for rec in results['data']:
        wr.writerow({
            'count': rec['count'],
            'source_ip': rec['source_ip'],
            'tags': ','.join(get_tags(rec)),
        })
    response_data = outf.getvalue()
    outf.close()

    response = make_response(response_data)
    response.headers['Content-type'] = 'text/plain'
    return response

@api.route('/intel_feed/', methods=['GET'])
@token_auth
def intel_feed():
    results = get_intel_feed()
    return jsonify(**results)

def get_intel_feed():
    options = request.args.to_dict()
    limit = int(options.get('limit', '1000'))
    hours_ago = int(options.get('hours_ago', '4'))

    extra = dict(options)
    for name in  ('hours_ago', 'limit', 'api_key',):
        if name in extra:
            del extra[name]

    for name in options.keys():
        if name not in ('hours_ago', 'limit',):
            del options[name]

    extra['ne__protocol'] = 'pcap'
    results = Clio().session._tops(['source_ip', 'honeypot', 'protocol', 'destination_port'], top=limit, hours_ago=hours_ago, **extra)
    results = [r for r in results if r['protocol'] != 'ftpdatalisten']

    cache = {}
    for r in results:
        source_ip = r['source_ip']
        if source_ip not in cache:
            # TODO: may want to make one big query to mongo here...
            cache[source_ip] = [m.to_dict() for m in Clio().metadata.get(ip=r['source_ip'], honeypot='p0f')]
        r['meta'] = cache[source_ip]

    return {
        'data':results,
        'meta':{
            'size': len(results),
            'query': 'intel_feed',
            'options': options
        }
    }


@api.route('/rule/<rule_id>/', methods=['PUT'])
@token_auth
def update_rule(rule_id):
    rule = Rule.query.filter_by(id=rule_id).first_or_404()
    for field in request.json.keys():
        if field in Rule.editable_fields():
            setattr(rule, field, request.json[field])
        elif field in Rule.fields():
            return error_response(
                    errors.API_FIELD_NOT_EDITABLE.format(field), 400)
        else:
            return error_response(
                    errors.API_FIELD_INVALID.format(field), 400)
    else:
        db.session.commit()
        return jsonify(rule.to_dict())


@api.route('/rule/', methods=['GET'])
@sensor_auth
def get_rules():
    # Getting active rules.
    if request.args.get('plaintext') in ['1', 'true']:
        # Requested rendered rules in plaintext.
        resp = make_response(Rule.renderall())

server/mhn/tasks/__init__.py
from celery import Celery

from mhn import mhn


celery = Celery(include=['mhn.tasks.rules'])
celery.conf.update(mhn.config)
TaskBase = celery.Task
class ContextTask(TaskBase):
    abstract = True
    def __call__(self, *args, **kwargs):
        with mhn.app_context():
            return TaskBase.__call__(self, *args, **kwargs)
celery.Task = ContextTask

server/mhn/templates/base.html
<!doctype html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <title>{% block extra_head %}{% endblock %}</title>
        <script src="/static/js/vendor/jquery.js"></script>
        <link rel="stylesheet" href="/static/css/foundation.min.css">
        <link rel="stylesheet" href="/static/css/normalize.css">
        <script src="/static/js/vendor/foundation.min.js"></script>
        <script src="/static/js/vendor/modernizr.js"></script>
        <script src="/static/js/main.js"></script>
    </head>
    <body>
        {% if user.is_authenticated %}
        <nav class="top-bar" style="margin-bottom: 30px;"  data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="{{ url_for('ui.dashboard') }}">MHN Server</a></h1>
                </li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li><a href="{{ url_for('ui.honeymap') }}">Map</a></li>
                    <li><a href="{{ url_for('ui.deploy_mgmt') }}">Deploy</a></li>
                    <li><a href="{{ url_for('ui.get_attacks') }}">Attacks</a></li>
                    <li><a href="{{ url_for('ui.get_feeds', channel='snort.alerts') }}">Payloads</a></li>
                    <li class="has-dropdown">
                        <a href="{{ url_for('ui.get_rules') }}">Rules</a>
                        <ul class="dropdown">
                            <li><label>Manage</label></li>
                            <li><a href="{{ url_for('ui.get_rules') }}">Activate/Deactivate</a></li>
                            <li><a href="{{ url_for('ui.rule_sources_mgmt') }}">Sources</a></li>
                            <li><label>Download</label></li>
                            <li><a href="{{ url_for('api.get_rules', plaintext=true) }}">Live Render</a></li>
                            <li><a href="/static/mhn.rules">Pre-Rendered</a></li>
                        </ul>
                    </li>
                    <li class="has-dropdown">
                        <a href="{{ url_for('ui.get_sensors') }}">Sensors</a>
                        <ul class="dropdown">
                            <li><a href="{{ url_for('ui.get_sensors') }}">View sensors</a></li>
                            <li><a href="{{ url_for('ui.add_sensor') }}">Add sensor</a></li>
                        </ul>
                    </li>
            
				
				
			 <li class="has-dropdown">
                        <a href="/ui/chart">Charts</a>
                        <ul class="dropdown">
                            <li><a href="/image/top_passwords.svg">Kippo/Cowrie Top Passwords</a></li>
                            <li><a href="/image/top_users.svg">Kippo/Cowrie Top Users</a></li>
                            <li><a href="/image/top_combos.svg">Kippo/Cowrie Top User/Passwords</a></li>
                            <li><a href="/image/top_sessions.svg">Kippo/Cowrie Top Attackers</a></li>
                        </ul>
                    </li>
                </ul>

				
				
				
                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="active"><a id="out-btn" href="#">LOGOUT</a></li>
                </ul>
                {% if current_user.has_role('admin') %}
                <ul class="right">
                    <li class=""><a id="out-btn" href="{{ url_for('ui.settings') }}">Settings</a></li>
                </ul>
                {% endif %}
            </section>
        </nav>
        {% endif %}
        {% block content %}{% endblock %}
        {% block footer %}
        <style>
            #footer {
                margin-top: 80px;
                margin-bottom: 80px;
                bottom: 0;
                width: 100%;
            }
        </style>
        <div class="row" id="footer">
            <div class="small-7 large-centered columns">
                <span><small>Modern Honeynet Framework is an open source project by: </small><span>
                <a href="http://threatstream.com"><img width="158" height="25" src="/static/img/tslogo.png" /></a>
            </div>
        </div>
        {% endblock %}
        <script src="/static/js/vendor/fastclick.js"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>

server/mhn/templates/pagination.html
{% macro render_pagination(items, view, args) %}
{% if items.pages > 1 %}
<div class="pagination-centered">
    <ul class="pagination">
        {% if items.page > 1 %}
        {% set _ = args.update({'page': items.page - 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&laquo;</a></li>
        {% endif %}
        {% for page in items.iter_pages() %}
        {% if not page %}
        <li class="unavailable" style="color:#999;">&hellip;</li>
        {% else %}
        {% set _ = args.update({'page': page}) %}
        <li class={% if page == items.page %}"current"{% endif %}>
            <a href="{{ url_for(view, **args) }}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if items.pages > items.page %}
        {% set _ = args.update({'page': items.page + 1}) %}
        <li class="arrow"><a href="{{ url_for(view, **args) }}">&raquo;</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endmacro %}